### ISSUE TITLE
Run the Examples Classification: Criteo, 报错

### ISSUE THREAD

**Issue by somTian** [shenweichen/DeepCTR#24] opened 2019-01-03 02:40 UTC
运行官网的例子时，报错信息为：
`tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0,0] = 104 is not in [0, 14)
	 [[{{node sparse_emb_18-C14/embedding_lookup}} = ResourceGather[Tindices=DT_INT32, _class=["loc:@training/Adam/gradients/sparse_emb_18-C14/embedding_lookup_grad/Reshape"], dtype=DT_FLOAT, validate_indices=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](sparse_emb_18-C14/embeddings, linear_emb_18-C14/Cast)]]`

系统版本：
tensorflow:1.11.0
keras:2.2.4
deepctr:0.2.2

**Comment by shenweichen** [comment] 2019-01-07 09:09
@silverstone1903 Hello, thanks for using.
I think this error  is caused by  the fact that the feature index in the sample is beyond the scope of the predefined Embedding dictionary. 
It is recommended that you consider all the samples when generating the feature configuration,or use hash encoder to map the features to a fixed length space.
You can check the example https://github.com/shenweichen/DeepCTR/blob/master/examples/run_classification_criteo.py

**Comment by silverstone1903** [comment] 2019-01-07 18:16
@shenweichen thanks for your answer. I guess I figured out what I did. I've separated train and test files. For label encoding and scaling I merged both of them. Then I created sparse_feature_dict with just train dataframe (probably first mistake). Seems like one variable has different unique category values between files (train:14, test:15, merged data have 16 values). That's why it gives this error I think. So here is my question: How should I do preprocess train and test files for proper model?

**Comment by shenweichen** [comment] 2019-01-07 18:20
@silverstone1903 You can check the example https://github.com/shenweichen/DeepCTR/blob/master/examples/run_classification_criteo.py  line 18 -36

**Closed** 2019-01-23 03:32 UTC

**Comment by daisy-belle** [comment] 2019-01-23 09:51
@somTian  请问您的问题已经解决了吗，我也遇到了同样的问题 
系统版本：
tensorflow:1.12
deepctr:0.2.2
没有Keras

**Comment by shenweichen** [comment] 2019-01-23 14:04
@daisy-belle ..你的问题还没解决掉么

**Comment by daisy-belle** [comment] 2019-01-24 02:49
@shenweichen 没有呢，这次是下载下来模型之后直接运行 run_classification_criteo.py, 没有修改代码，出现了以下错误：
WARNING:tensorflow:From C:\work\project\learn_test\DeepCTR-master\deepctr\layers.py:411: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Train on 128 samples, validate on 32 samples
Epoch 1/1
2019-01-24 10:45:52.841600: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "C:/work/project/learn_test/DeepCTR-master/examples/run_classification_criteo.py", line 45, in <module>
    batch_size=256, epochs=1, verbose=2, validation_split=0.2, )
  File "C:\ProgramData\Anaconda2\envs\py3\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1639, in fit
    validation_steps=validation_steps)
  File "C:\ProgramData\Anaconda2\envs\py3\lib\site-packages\tensorflow\python\keras\engine\training_arrays.py", line 215, in fit_loop
    outs = f(ins_batch)
  File "C:\ProgramData\Anaconda2\envs\py3\lib\site-packages\tensorflow\python\keras\backend.py", line 2986, in __call__
    run_metadata=self.run_metadata)
  File "C:\ProgramData\Anaconda2\envs\py3\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)
  File "C:\ProgramData\Anaconda2\envs\py3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[1,0] = 133 is not in [0, 125)
	 [[{{node sparse_emb_9-C24/embedding_lookup}} = ResourceGather[Tindices=DT_INT32, _class=["loc:@training/Adam/gradients/sparse_emb_9-C24/embedding_lookup_grad/Reshape"], dtype=DT_FLOAT, validate_indices=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](sparse_emb_9-C24/embeddings, linear_emb_9-C24/Cast)]]

不知道是否跟系统和版本有关系
64位window7专业版
tensorflow 1.12.0   没有GPU，运行的CPU版本
deepctr 0.2.2

**Comment by shenweichen** [comment] 2019-01-24 03:55
@daisy-belle 你的python版本是什么，deepctr是从pip上安装的吗

**Comment by daisy-belle** [comment] 2019-01-24 07:01
@shenweichen python3.5.2， deepctr使用pip安装的

**Comment by shenweichen** [comment] 2019-01-24 07:05
@daisy-belle 方便的话给我发下邮件吧 wcshen1994@163.com 我看看具体什么情况
